apiVersion: v1
kind: Service
metadata:
  name: biome-storybook
  labels:
    app.kubernetes.io/name: biome-storybook
    app.kubernetes.io/part-of: pseg
    app.kubernetes.io/component: documentation
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app.kubernetes.io/name: biome-storybook
